"""用户表，email 可为空

Revision ID: 9bcc4f785325
Revises: 19dfe76188cb
Create Date: 2025-08-21 15:06:48.872763

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9bcc4f785325"
down_revision = "19dfe76188cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="雪花ID主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="邮箱",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="邮箱",
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BIGINT(),
        comment="雪花ID主键",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
